import { defineField, defineType } from 'sanity'

export default defineType({
  name: 'caseStudy',
  title: 'Case Study',
  type: 'document',
  groups: [
    { name: 'properties', title: 'Properties', default: true },
    { name: 'content', title: 'Main Content' },
    { name: 'extras', title: 'Extra Content' },
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      group: 'properties',
      description: 'The case study headline shown on the listing card and page header',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'heading',
      title: 'Page Heading',
      type: 'string',
      group: 'properties',
      description: 'Override title for the page h1 (defaults to title if empty)',
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      group: 'properties',
      description: 'URL path segment (e.g. "hgraph" → /work/hgraph). Click Generate.',
      options: { source: 'title', maxLength: 96 },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'client',
      title: 'Client',
      type: 'string',
      group: 'properties',
      description: 'Client or partner name shown beneath the title',
    }),
    defineField({
      name: 'hideClientSubtitle',
      title: 'Hide Client Subtitle',
      type: 'boolean',
      group: 'properties',
      description: 'Hide the "for {client}" subtitle on the page header while keeping the client metadata for other uses',
      initialValue: false,
    }),
    defineField({
      name: 'image',
      title: 'Hero Image',
      type: 'image',
      group: 'properties',
      description: 'Primary image used on the card and page hero. Recommended: 1600×900 px. The hotspot (crosshair) marks the focal point that stays visible when cropped for cards or mobile.',
      options: { hotspot: true },
    }),
    defineField({
      name: 'caption',
      title: 'Caption',
      type: 'text',
      rows: 3,
      group: 'properties',
      description: 'Short summary shown on the listing card (1-2 sentences)',
    }),
    defineField({
      name: 'categories',
      title: 'Categories',
      type: 'array',
      group: 'extras',
      description: 'Tag this case study with one or more categories for filtering',
      of: [{ type: 'reference', to: [{ type: 'category' }] }],
    }),
    defineField({
      name: 'displayTags',
      title: 'Display Tags',
      type: 'string',
      group: 'extras',
      description: 'Optional curated tag line shown on the case study page (separate from taxonomy categories used for filtering)',
    }),
    defineField({
      name: 'metadataLayout',
      title: 'Metadata Layout',
      type: 'string',
      group: 'extras',
      description: 'How Time and Tags should be grouped on the case study page',
      options: {
        list: [
          { title: 'Stacked', value: 'stacked' },
          { title: 'Inline', value: 'inline' },
        ],
        layout: 'radio',
      },
      initialValue: 'stacked',
    }),
    defineField({
      name: 'authors',
      title: 'Authors',
      type: 'array',
      group: 'extras',
      description: 'Team members who authored this case study',
      of: [{ type: 'reference', to: [{ type: 'teamMember' }] }],
    }),
    defineField({
      name: 'content',
      title: 'Content',
      type: 'portableText',
      group: 'content',
      description: 'Full case study body — use headings, images, columns, and quotes',
    }),
    defineField({
      name: 'upNext',
      title: 'Up Next',
      type: 'array',
      group: 'extras',
      description: 'Related case studies or vision articles shown at the bottom',
      of: [{ type: 'reference', to: [{ type: 'caseStudy' }, { type: 'feature' }] }],
    }),
    defineField({
      name: 'time',
      title: 'Time',
      type: 'string',
      group: 'extras',
      description: 'Project duration (e.g. "1.5 designers for 6 months")',
    }),
    defineField({
      name: 'hidden',
      title: 'Hidden',
      type: 'boolean',
      group: 'properties',
      description: 'Hide this case study from the /work listing (it can still be accessed by URL)',
      initialValue: false,
    }),
    defineField({
      name: 'metaDescription',
      title: 'Meta Description',
      type: 'text',
      rows: 3,
      group: 'properties',
      description: 'SEO description for search engines (max ~160 characters)',
    }),
    defineField({
      name: 'order',
      title: 'Sort Order',
      type: 'number',
      group: 'properties',
      description: 'Display position on the /work page (lower numbers appear first)',
    }),
  ],
  orderings: [
    {
      title: 'Sort Order',
      name: 'orderAsc',
      by: [{ field: 'order', direction: 'asc' }],
    },
  ],
  preview: {
    select: {
      title: 'title',
      subtitle: 'client',
      media: 'image',
    },
  },
})
