import type { Metadata } from 'next'
import Image from 'next/image'
import { cloudfrontImage } from '@/lib/utils'
import { Divider } from '@/components/ui/Divider'
import { Author } from '@/components/ui/Author'
import { Button } from '@/components/ui/Button'
import { NewsletterForm } from '@/components/forms/NewsletterForm'
import { SetCaseStudyHero } from '@/components/work/SetCaseStudyHero'
import { References } from '@/components/ui/References'
import refs from '@/data/vision/own-your-health-data/references.json'

export const metadata: Metadata = {
  title: 'Own Your Health Data',
  description:
    'As the future of our healthcare system moves towards electronic healthcare records, we need patient data ownership rights to protect patient care.',
}

export default function OwnYourHealthDataPage() {
  return (
    <div>
      <SetCaseStudyHero
        image={cloudfrontImage(
          '/images/features/own-your-health-data/patient-data-ownership.jpg'
        )}
      />

      {/* Content */}
      <section className="py-12">
        <div className="max-width max-width-md content-padding mx-auto">
          <h1 className="font-serif text-[1.75rem] leading-[2.0625rem] lg:text-[2.25rem] lg:leading-[2.625rem] font-light">
            Own Your Health Data
          </h1>
          <p className="text-gray leading-relaxed mb-4">
            As the future of our healthcare system moves towards electronic
            healthcare records, we need patient data ownership rights to protect
            patient care.
          </p>

          <h4 className="header-md mb-2">4 Principles</h4>
          <p className="leading-relaxed mb-4">
            1. Patients co-own or fully own every health data point about
            themselves.
          </p>
          <p className="leading-relaxed mb-4">
            2. Health data generated about the patient by a provider is co-owned
            by both parties.
          </p>
          <p className="leading-relaxed mb-4">
            3. Health data generated by the patient is fully owned by the patient
            with a right to possess, share, sell, or destroy.
          </p>
          <p className="leading-relaxed mb-4">
            4. All uses of a patients&apos; health data shall be consented in
            advance by the patient, other than uses required by law.
          </p>
        </div>

        <div className="max-width max-width-md content-padding mx-auto">
          <div className="mb-8">
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 mt-8">
              <div>
                <a
                  href={cloudfrontImage(
                    '/pdf/vision/own-your-health-data/Own-Your-Health-Data.pdf'
                  )}
                >
                  <Image
                    src={cloudfrontImage(
                      '/images/features/own-your-health-data/cover.jpg'
                    )}
                    alt="Own Your Health Data Comic Cover"
                    width={800}
                    height={1000}
                    className="w-full h-auto"
                  />
                </a>
                <Button
                  href={cloudfrontImage(
                    '/pdf/vision/own-your-health-data/Own-Your-Health-Data.pdf'
                  )}
                  variant="secondary"
                  className="w-full mt-8 mb-2"
                >
                  Download Comic
                </Button>
                <div className="mt-4 text-center">
                  <a
                    href="https://github.com/goinvo/OwnYourHealthData"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-secondary hover:text-primary"
                  >
                    On GitHub
                  </a>
                </div>
              </div>
              <div>
                <a
                  href="https://docs.google.com/document/d/13j03-beeoOZujMK6smdjcicKAb1Jh_L6tn_NG91Nq4M/edit"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <Image
                    src={cloudfrontImage(
                      '/images/features/own-your-health-data/own-your-health-data-whitepaper-cover.jpg'
                    )}
                    alt="Own Your Health Data Whitepaper Cover"
                    width={800}
                    height={1000}
                    className="w-full h-auto"
                  />
                </a>
                <Button
                  href="https://docs.google.com/document/d/13j03-beeoOZujMK6smdjcicKAb1Jh_L6tn_NG91Nq4M/edit"
                  variant="secondary"
                  external
                  className="w-full mt-8 mb-2"
                >
                  View Whitepaper
                </Button>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Feedback Section */}
      <section className="py-12">
        <div className="max-width max-width-md content-padding mx-auto">
          <h2 className="font-serif text-2xl text-center mb-2 mt-8">
            We&apos;d Like Your Feedback
          </h2>
          <p className="text-gray leading-relaxed mb-4">
            We&apos;ve mapped out the needs for owning your health data and have
            illustrated them to be digestible for policy makers and the general
            public. If you have any feedback, please share with{' '}
            <a
              href="mailto:hello@goinvo.com"
              className="text-secondary hover:text-primary"
            >
              hello@goinvo.com
            </a>
            .
          </p>

          <h4 className="header-md mb-2 mt-8">About GoInvo</h4>
          <p className="text-gray leading-relaxed mb-4">
            GoInvo is a healthcare design company that crafts innovative digital
            and physical solutions. Our deep expertise in Health IT, Genomics,
            and Open Source health has delivered results for the National
            Institutes of Health, Walgreens, Mount Sinai, and Partners
            Healthcare.
          </p>
        </div>
      </section>

      {/* Authors */}
      <section className="py-12">
        <div className="max-width max-width-md content-padding mx-auto">
          <h2 className="font-serif text-[1.75rem] leading-[2.0625rem] lg:text-[2.25rem] lg:leading-[2.625rem] font-light text-center">
            Authors
          </h2>
          <Author name="Annie Lakey Becker">
            Annie is a Mom, Product and Project Manager based in Seattle.
            Passionate about Public Health and systems, her background includes
            roles as an academic research scientist and patient-focused
            neurodiagnostic technologist. She has a BS in Public Health from the
            University of Washington and is completing a Masters in Public Health
            at UNC Chapel Hill.
          </Author>
          <Author name="Kim Nipp">
            Kim is a designer, illustrator, and animator specializing in
            scientific visualization. Originally trained in behavioural
            neuroscience at the University of British Columbia, Kim moved on to
            complete their Masters of Science in Biomedical Communications, an
            interdisciplinary graduate program for visual media design in science
            and medicine offered through the Faculty of Medicine at the
            University of Toronto.
          </Author>
          <Author name="Megan Hirsch" />
          <Author name="Juhan Sonin" />

          <div className="py-8">
            <h3 className="header-md">Contributors</h3>
            <p className="leading-relaxed">
              Eric Benoit
              <br />
              Kathy Mikk
              <br />
              Harry Sleeper
              <br />
              Colleen Tang Poy
            </p>
          </div>
        </div>
      </section>

      {/* Newsletter */}
      <section className="bg-gray-100 py-12">
        <div className="max-width max-width-md content-padding mx-auto">
          <NewsletterForm />
        </div>
      </section>

      {/* References */}
      <section className="py-12">
        <div className="max-width max-width-md content-padding mx-auto">
          <References items={refs} />
        </div>
      </section>
    </div>
  )
}
